const std = @import("std");
const zqlite = @import("zqlite");

pub fn main(init: std.process.Init) !void {
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    var cwd = std.Io.Dir.cwd();
    try cwd.createDirPath(init.io, "tests/standalone/fixtures/pqc/generated/ml-kem-768");
    try cwd.createDirPath(init.io, "tests/standalone/fixtures/pqc/generated/ml-dsa-65");

    const backend = zqlite.pqc_backend.StdlibPQCBackend.backend;
    try writeKemFixture(init.io, allocator, backend, "tests/standalone/fixtures/pqc/generated/ml-kem-768/zqlite-stdlib-001.kat");
    try writeSignFixture(init.io, allocator, backend, "tests/standalone/fixtures/pqc/generated/ml-dsa-65/zqlite-stdlib-001.kat");
    try writeReadme(init.io);

    std.debug.print("Generated PQC regression KAT fixtures under tests/standalone/fixtures/pqc/generated/\n", .{});
}

fn writeKemFixture(io: std.Io, allocator: std.mem.Allocator, backend: zqlite.pqc_backend.PQCBackend, path: []const u8) !void {
    var key_seed: [zqlite.pqc_backend.MlKem768.key_seed_length]u8 = undefined;
    for (&key_seed, 0..) |*byte, i| byte.* = @intCast((i * 19 + 1) & 0xff);

    var encaps_seed: [zqlite.pqc_backend.MlKem768.encaps_seed_length]u8 = undefined;
    for (&encaps_seed, 0..) |*byte, i| byte.* = @intCast((i * 23 + 5) & 0xff);

    const kp = try backend.kemKeypair(allocator, &key_seed);
    defer kp.deinit(allocator);
    const encapsulated = try backend.kemEncaps(allocator, kp.public_key, &encaps_seed);
    defer encapsulated.deinit(allocator);

    var file = try std.Io.Dir.cwd().createFile(io, path, .{ .truncate = true });
    defer file.close(io);
    var buffer: [4096]u8 = undefined;
    var writer = file.writer(io, &buffer);
    const out = &writer.interface;
    defer out.flush() catch {};

    try out.writeAll("# ZQLite-generated stdlib backend regression vector. Not official.\n");
    try out.writeAll("suite = ml-kem-768\n");
    try out.writeAll("source = zqlite-stdlib\n");
    try out.writeAll("classification = generated\n");
    try writeHexField(out, "key_seed", &key_seed);
    try writeHexField(out, "encaps_seed", &encaps_seed);
    try writeHexField(out, "expected_public_key", kp.public_key);
    try writeHexField(out, "expected_secret_key", kp.secret_key);
    try writeHexField(out, "expected_ciphertext", encapsulated.ciphertext);
    try writeHexField(out, "expected_shared_secret", encapsulated.shared_secret);
}

fn writeSignFixture(io: std.Io, allocator: std.mem.Allocator, backend: zqlite.pqc_backend.PQCBackend, path: []const u8) !void {
    var seed: [zqlite.pqc_backend.MlDsa65.seed_length]u8 = undefined;
    for (&seed, 0..) |*byte, i| byte.* = @intCast((i * 31 + 7) & 0xff);
    const message = "zqlite generated ml-dsa-65 regression vector";

    const kp = try backend.signKeypair(allocator, &seed);
    defer kp.deinit(allocator);
    const signature = try backend.sign(allocator, message, kp.secret_key);
    defer allocator.free(signature);

    var file = try std.Io.Dir.cwd().createFile(io, path, .{ .truncate = true });
    defer file.close(io);
    var buffer: [4096]u8 = undefined;
    var writer = file.writer(io, &buffer);
    const out = &writer.interface;
    defer out.flush() catch {};

    try out.writeAll("# ZQLite-generated stdlib backend regression vector. Not official.\n");
    try out.writeAll("suite = ml-dsa-65\n");
    try out.writeAll("source = zqlite-stdlib\n");
    try out.writeAll("classification = generated\n");
    try writeHexField(out, "seed", &seed);
    try out.print("message = {s}\n", .{message});
    try writeHexField(out, "expected_public_key", kp.public_key);
    try writeHexField(out, "expected_secret_key", kp.secret_key);
    try writeHexField(out, "expected_signature", signature);
}

fn writeReadme(io: std.Io) !void {
    var file = try std.Io.Dir.cwd().createFile(io, "tests/standalone/fixtures/pqc/generated/README.md", .{ .truncate = true });
    defer file.close(io);
    var buffer: [1024]u8 = undefined;
    var writer = file.writer(io, &buffer);
    const out = &writer.interface;
    defer out.flush() catch {};

    try out.writeAll(
        \\# Generated PQC Regression Fixtures
        \\
        \\These files are generated by `zig build generate-pqc-regression-kats`.
        \\
        \\They are deterministic ZQLite stdlib-backend regression vectors, not official NIST/ACVP vectors and not liboqs vectors.
        \\
        \\Run them with:
        \\
        \\```bash
        \\zig build test-pqc-generated-kats --summary all
        \\```
        \\
    );
}

fn writeHexField(out: *std.Io.Writer, name: []const u8, data: []const u8) !void {
    try out.print("{s} = ", .{name});
    for (data) |byte| {
        try out.print("{x:0>2}", .{byte});
    }
    try out.writeByte('\n');
}
